build_prod:
  cmd: docker build
  force_rm: true
  tags:
    - registry: &REGISTRY docker-registry.dun.fh
      image: &IMAGE_NAME findmypast/usher
      tag: latest
    - registry: *REGISTRY
      image: *IMAGE_NAME
      tag: <%=version%>

fast_tests:
  cmd: npm test

# docker build
# --force-rm
# --file=Dockerfile.test
# --tag %docker.repository%-test:%teamcity.build.branch%
# .
