vars:
  registry: docker-registry.dun.fh
  image: findmypast/usher

tasks:
  build:
    - description: Build the container
    - cmd: docker build --force-rm -t <%=registry%>/<%=image%>:<%=version%> .
      description: subdescription

  push:
    - cmd: docker push <%=registry%>/<%=image%>:<%=version%>

  test:
    - description: Run unit tests
    - cmd: docker run --name usher-test-runner --rm <%=registry%>/<%=image%>:<%=version%> npm run test:ci

  publish:
    - cmd: docker run -e NPM_USER -e NPM_PASSWORD -e NPM_EMAIL --name usher-publisher --rm <%=registry%>/<%=image%>:<%=version%> npm run publish-to-npm
      environment:
        - NPM_USER=<%=user%>
        - NPM_PASSWORD=<%=password%>
        - NPM_EMAIL=<%=email%>
