build:
  cmd: docker build
  force_rm: true
  tags:
    - registry: &REGISTRY docker-registry.dun.fh
      image: &IMAGE_NAME findmypast/usher
      tag: <%=version%>
    - registry: *REGISTRY
      image: *IMAGE_NAME
      tag: latest

push:
  - cmd: docker push
    registry: *REGISTRY
    image: *IMAGE_NAME
    tag: <%=version%>
  - cmd: docker push
    registry: *REGISTRY
    image: *IMAGE_NAME
    tag: latest

test:
  cmd: docker run
  name: usher-test-runner
  remove: true
  target:
    registry: *REGISTRY
    image: *IMAGE_NAME
    tag: latest
  container_command: npm test

publish:
  cmd: docker run
  name: usher-publisher
  environment:
    - NPM_USER=<%=user%>
    - NPM_PASSWORD=<%=password%>
    - NPM_EMAIL=<%=email%>
  remove: true
  target:
    registry: *REGISTRY
    image: *IMAGE_NAME
    tag: latest
  container_command: npm run publish-to-npm
