build_prod:
  cmd: docker build
  force_rm: true
  tags:
    - registry: &REGISTRY docker-registry.dun.fh
      image: &IMAGE_NAME findmypast/usher
      tag: latest
    - registry: *REGISTRY
      image: *IMAGE_NAME
      tag: <%=version%>

fast_tests:
  cmd: npm test

# docker build
# --force-rm
# --file=Dockerfile.test
# --tag %docker.repository%-test:%teamcity.build.branch%
# .

run_prod:
  cmd: docker run
  environment:
    - node-env=prod
  memory: 256M
  name: usher
  publish:
    - client: 80
      host: 80
    - client: 8080
      host: 8080
  target:
    registry: *REGISTRY,
    image: *IMAGE_NAME,
    tag: test
  container_command: npm test
