vars:
  registry: docker-registry.dun.fh
  image: findmypast/usher

tasks:
  build:
    cmd: docker build --force-rm -t <%=registry%>/<%=image%>:<%=version%> .

  push:
    cmd: docker push <%=registry%>/<%=image%>:<%=version%>

  test:
    cmd: docker run --name usher-test-runner --rm <%=registry%>/<%=image%>:<%=version%>  npm test

  publish:
    cmd: docker run --name usher-publisher --rm <%=registry%>/<%=image%>:<%=version%> npm run publish-to-npm
    environment:
      - NPM_USER=<%=user%>
      - NPM_PASSWORD=<%=password%>
      - NPM_EMAIL=<%=email%>
