build:
  cmd: docker build
  force_rm: true
  tags:
    - findmypast/usher

fast_tests:
  cmd: npm test



# docker build
# --force-rm
# --file=Dockerfile.test
# --tag %docker.repository%-test:%teamcity.build.branch%
# .
