build:
  cmd: docker build
  force_rm: true
  tags:
    - registry: &REGISTRY asdf
      image: &IMAGE_NAME asdf
      tag: <%=version%>

push:
  cmd: docker push
  registry: *REGISTRY
  image: *IMAGE_NAME
  tag: <%=version%>

test:
  cmd: docker run
  name: {projectName}}-test-runner
  remove: true
  target: &TARGET
    registry: *REGISTRY
    image: *IMAGE_NAME
    tag: <%=version%>
  container_command: 

local:
  - cmd: docker rm -f asdf-local
    ignore_errors:
        - 1
  - cmd: docker run
    name: asdf-local
    memory: 256M
    publish:
      - client: 8080
        host: 8080
    detach: true
    target: *TARGET

deploy:
  - cmd: docker -H sdfgsdfgsdgf rm -f asdf
    ignore_errors:
      - 1
  - cmd: docker run
    name: asdf
    memory: 256M
    publish:
      - client: 8080
        host: 80
    environment:
      - SERVICE_NAME=asdf
      - SERVICE_TAGS=production
      - SERVICE_CHECK_HTTP=/health
      - SERVICE_CHECK_INTERVAL=60s
    restart: always
    detach: true
    host: sdfgsdfgsdgf
    target: *TARGET
