@startuml
title Build pipeline
start
:Code committed;
:Build container;

if (Build success) then (yes)
else (no)
  end
endif

:Publish container;

if(Publish success) then (yes)
else(no)
  end
endif

:Run fast tests;

if(Fast tests success) then (yes)
else(no)
  end
endif

:Run slow tests;

if(Slow tests success) then (yes)
else(no)
  end
endif

:Run container locally;
:Run acceptance tests
against local container;
:Teardown local container;

if(Accetpance tests success) then (yes)
else(no)
  end
endif

:Deploy to integration;
:Deploy to production;

stop

@enduml
